# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "npm"
   directory: "/"
   schedule:
     interval: weekly

  # Configure pull request settings
  open-pull-requests-limit: 1  # Maximum number of open pull requests Dependabot should have at any time
  commit-message:
    prefix: "chore"      # Prefix for the commit message and pull request title (e.g., chore, fix)
    include: "scope"     # Include the scope of the dependency in the commit message