services:
  web:
    # Build the Docker image using the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    image: your-registry/your-image-name:tag
    # Map port 8080 on the host to port 80 in the container
    ports:
      - "8080:80"
    # Set the restart policy to ensure the service restarts if it goes down
    restart: unless-stopped
